config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "staticpages#home"
  get "/help", to: "staticpages#help"
  get "/terms", to: "staticpages#terms"
  get "/contact", to: "staticpages#contact"
  get "/search", to: "microposts#search"
  get "/sample", to: "users#sample"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :following, :followers] do
    member do
      get :following, :followers
    end
  end
  resources :microposts
  resources :subcategories, only: [:show]
  resources :scores, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :infos, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :profile, length: { maximum: 200 }
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :replies, dependent: :destroy
  has_many :infos, dependent: :destroy

   def self.find_for_oauth(auth)
     user = User.where(uid: auth.uid, provider: auth.provider).first
     unless user
       user = User.create(
         uid:      auth.uid,
         provider: auth.provider,
         email:    User.dummy_email(auth),
         name:  auth.info.name,
         password: Devise.friendly_token[0, 20],
         remote_image_url:  auth.info.image.gsub("picture","picture?type=large")
       )
     end
     user
   end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

   private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at desc').page(params[:page]).per(5)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  def sample
    sample_user = User.find(1)
    sign_in sample_user
    flash[:success] = "サンプルユーザーでのログインに成功しました"
    redirect_to sample_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_btn.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-secondary" %>
<% end %>

app/views/users/_user.html.erb
<div class="panel panel-default">
  <%= link_to user_path(user) do%>
    <div class="panel-body panel-follow">
      <img src=<%= user.image %> class = "icon_midium_image">
      <h3><%= user.name %>
    </div>
  <% end %>
</div>

app/views/users/_user_show.html.erb
<%= link_to user_path(@user) do %>
  <img src=<%= @user.image %> class = "icon_image">
<% end %>
<% if user_signed_in? %>
  <div class="follow_btn">
    <%= render 'follow_btn'%>
  </div>
<% end %>
<div class="stats">
  <%= link_to followers_user_path(@user) do %>
    <button class="btn btn-info" type="button">
    フォロワー <span class="badge" id="followers"><%= @user.followers.count %></span>
    </button>
  <% end %>
  <%= link_to following_user_path(@user) do %>
    <button class="btn btn-info" type="button">
    フォロー <span class="badge" id="following" ><%= @user.following.count %></span>
    </button>
  <% end %>
</div>
<h3><名前> <br>
<%= @user.name %></h3>
<h3><プロフィール> </h3>
<p><%= @user.profile %></p>
<% if @user == current_user %>
  <div class="new-post-btn">
    <%= link_to new_micropost_path do %>
      <p><button type="button" class="btn btn-success">動画を投稿する</button></p>
    <% end %>
  </div>
  <% unless current_user == User.find(1) %>
    <%= link_to "プロフィール編集", edit_user_registration_path(current_user.id) %>
  <% else %>
    <p>サンプルユーザーはプロフィールの編集ができません</p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div clas="row">
  <div class="col-md-4 col-sm-5 col-xs-12 sideBar">
    <div class="user-side">
      <%= render 'user_show' %>
    </div>
  </div>
  <% if @microposts.present? %>
    <div class="col-md-8 col-sm-7 col-xs-12">
      <%= render @microposts %>
      <%= paginate @microposts %>
    </div>
  <% else %>
    <div class="non">
      <h3>まだ投稿がありません</h3>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<div clas="row">
  <div class="col-md-4 col-sm-5 col-xs-12 sideBar">
    <div class ="user-side">
      <%= render 'user_show' %>
    </div>
  </div>
  <div class="col-md-8 col-sm-7 col-xs-12">
    <% if @users.any? %>
      <%= render @users %>
      <%= paginate @users %>
    <% else %>
      <h3 class="recommend">友達を見つけましょう</h3>
    <% end %>
  </div>
</div>