config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "staticpages#home"
  get "/help", to: "staticpages#help"
  get "/terms", to: "staticpages#terms"
  get "/contact", to: "staticpages#contact"
  get "/search", to: "microposts#search"
  get "/sample", to: "users#sample"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :following, :followers] do
    member do
      get :following, :followers
    end
  end
  resources :microposts
  resources :subcategories, only: [:show]
  resources :scores, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :infos, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
end

app/models/info.rb
class Info < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  def action_user
    User.find(self.action_user_id)
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :user_id, presence: true
  validates :title,   presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :subcategory
  has_many :scores, dependent: :destroy
  has_many :replies, dependent: :destroy

  def self.search(search)
    if search
      Micropost.where(['content LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Micropost.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  validates  :content, presence: true
  belongs_to :micropost
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :microposts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :profile, length: { maximum: 200 }
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :replies, dependent: :destroy
  has_many :infos, dependent: :destroy

   def self.find_for_oauth(auth)
     user = User.where(uid: auth.uid, provider: auth.provider).first
     unless user
       user = User.create(
         uid:      auth.uid,
         provider: auth.provider,
         email:    User.dummy_email(auth),
         name:  auth.info.name,
         password: Devise.friendly_token[0, 20],
         remote_image_url:  auth.info.image.gsub("picture","picture?type=large")
       )
     end
     user
   end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

   private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :authenticate_user!

  def index
    @infos = current_user.infos.page(params[:page]).per(10)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!
  def create
    score = Score.new(score_params)
    @micropost = Micropost.find(params[:micropost_id])
    score.user_id = current_user.id
    score.micropost_id = @micropost.id

    if score.save
      flash[:success] = "採点しました"
      @micropost.averagescore = average_score(@micropost)
      @micropost.save
      redirect_to @micropost
    else
      flash[:danger] = "失敗しました"
      redirect_to @micropost
    end
  end

  def destroy
  end

  private
   def score_params
     params.require(:score).permit(:point)
   end

   def average_score(micropost)
     sum = 0
     micropost.scores.each do |score|
       sum += score.point
     end
     count = Score.where('cast(micropost_id as text) LIKE ?', "#{micropost.id}").count
     if count != 0
       (sum * 1.0/count * 1.0 ).round(1)
     else
       0
     end
   end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    @users = User.find(Relationship.group(:followed_id).order('count(followed_id) desc').limit(4).pluck(:followed_id))
    @new_post = Micropost.all.order('created_at desc').take(3)
    @popular_post = Micropost.all.order('averagescore desc').take(3)
  end

  def help
  end

  def terms
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at desc').page(params[:page]).per(5)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  def sample
    sample_user = User.find(1)
    sign_in sample_user
    flash[:success] = "サンプルユーザーでのログインに成功しました"
    redirect_to sample_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "わらログ"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def average_score(micropost)
    sum = micropost.scores.sum(&:point)
    count = Score.where('cast(micropost_id as text) LIKE ?', "#{micropost.id}").count
    if count != 0
      (sum * 1.0/count * 1.0 ).round(1)
    else
      0
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/staticpages/contact.html.erb
<ul>
  <li>氏名：　清水大夢</li>
  <li>Twitter：<%= link_to "https://twitter.com/time_shazam", "https://twitter.com/time_shazam" %></li>
  <li>github: <%= link_to "https://github.com/time-shimizu", "https://github.com/time-shimizu" %></li>
</ul>

app/views/staticpages/help.html.erb
<% provide(:title, "ヘルプ") %>
<div class="panel panel-primary">
  <div class="panel-heading">ヘルプ</div>
  <div class="panel-body">
    <p>このサイトは誰でも無料で閲覧、投稿することが可能です。</p>
    <p>動画投稿、採点、返信するには、会員登録(無料)が必要です。</p>
    <%= link_to "TOPに戻る", root_path %> |
    <%= link_to "会員登録",  new_user_registration_path %>
  </div>
</div>

app/views/staticpages/home.html.erb
<% unless user_signed_in? %>
  <section class="top-wrapper">
    <h1>みんなでネタを評価しあおう！！</h1>
    <div class="top-description">
    <p>漫才、コント、ピン芸まで色々なネタを投稿して</p>
    <p>みんなに見てもらい、意見を貰おう！</p>
    <%= link_to new_user_session_path do %>
      <p><button type="button" class="btn btn-primary navbar-btn">ログイン</button></p>
    <% end %>
    <%= link_to user_facebook_omniauth_authorize_path do %>
      <p><button type="button" class="btn btn-primary navbar-btn"><span class="fab fa-facebook"></span> facebookでログイン</button></p>
    <% end %>
    <%= link_to sample_path do %>
      <p><button type="button" class="btn btn-primary navbar-btn">サンプルユーザーでログイン</button></p>
    <% end %>
    </div>
  </section>
<% end %>
<h2><span class="glyphicon glyphicon-pencil"></span>新着ネタ</h2>
<hr>
<div class="row">
  <% @new_post.each do |micropost| %>
    <div class="col-md-4 col-xs-12 postBlock">
      <div class="postBox">
        <%= link_to micropost_path(micropost) do%>
          <div class="postCaption">
            <h3><%= micropost.title %></h3>
          </div>
          <div class="postFrame">
            <iframe width="288" height="162" src="https://www.youtube.com/embed/<%= micropost.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<h2><span class="fa fa-chess-king"></span>人気ネタ</h2>
<hr>
<div class="row">
  <% @popular_post.each do |post| %>
    <div class="col-md-4 col-xs-12 postBlock">
      <div class="postBox">
        <%= link_to micropost_path(post) do%>
          <div class="postCaption">
            <h3><%= post.title %></h3>
          </div>
          <div class="postFrame">
            <iframe width="288" height="162" src="https://www.youtube.com/embed/<%= post.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <p><button type="button" class="btn btn-default ">
            <span class="far fa-star"></span> <%= average_score(post) %>
          </button></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<h2><span class="fa fa-grin-wink"></span>人気ユーザー</h2>
<hr>
<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3 col-sm-6 col-xs-12 userBlock">
      <div class="userBox">
        <%= link_to user_path(user) do%>
          <div class="userImage">
            <img src=<%= user.image %> class = "icon_image">
          </div>
          <div class="userCaption">
            <h4><%= user.name %></h4>
            <button class="btn btn-info" type="button">
            フォロワー <span class="badge" id="followers"><%= user.followers.count %></span>
            </button>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/staticpages/terms.html.erb
<% provide(:title, "利用規約") %>
<h2>利用規約</h2>
<p>この利用規約（以下，「本規約」といいます。）は，わらログ（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

<h2>第1条（適用）</h2>
<p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>
<p>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</p>
<p>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</p>
<h2>第2条（利用登録）</h2>
<p>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。
当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
<ul>
<li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
<li>本規約に違反したことがある者からの申請である場合</li>
<li>その他，当社が利用登録を相当でないと判断した場合</li>
</ul>
<h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
<p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</p>
<p>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</p>
<p>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</p>
<h2>第4条（利用料金および支払方法）</h2>
<p>ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</p>
<p>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</p>
<h2>第5条（禁止事項）</h2>
<p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
<ul>
<li>法令または公序良俗に違反する行為</li>
<li>犯罪行為に関連する行為</li>
<li>当社，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
<li>当社のサービスの運営を妨害するおそれのある行為</li>
<li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
<li>不正アクセスをし，またはこれを試みる行為</li>
<li>他のユーザーに成りすます行為</li>
<li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
<li>当社，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
<li>以下の表現を含み，または含むと当社が判断する内容を本サービス上に投稿し，または送信する行為</li>
<li>過度に暴力的な表現</li>
<li>露骨な性的表現</li>
<li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
<li>自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
<li>その他反社会的な内容を含み他人に不快感を与える表現</li>
<li>以下を目的とし，または目的とすると当社が判断する行為</li>
<li>営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。）</li>
<li>性行為やわいせつな行為を目的とする行為</li>
<li>面識のない異性との出会いや交際を目的とする行為</li>
<li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
<li>当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
<li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
<li>宗教活動または宗教団体への勧誘行為</li>
<li>その他，当社が不適切と判断する行為</li>
</ul>
<h2>第6条（退会）</h2>
<p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
<h2>第7条（サービス内容の変更等）</h2>
<p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
<h2>第8条（利用規約の変更）</h2>
<p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>
<h2>第9条（個人情報の取扱い）</h2>
<p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
<h2>第10条（通知または連絡）</h2>
<p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
<h2>第11条（権利義務の譲渡の禁止）</h2>
<p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
<h2>第12条（準拠法・裁判管轄）</h2>
<p>本規約の解釈にあたっては，日本法を準拠法とします。</p>
<p>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</p>
<hr>
<h3><%= link_to "参考サイト", "https://kiyaku.jp/hinagata/sns.html" %></h3>