config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "staticpages#home"
  get "/help", to: "staticpages#help"
  get "/terms", to: "staticpages#terms"
  get "/contact", to: "staticpages#contact"
  get "/search", to: "microposts#search"
  get "/sample", to: "users#sample"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :following, :followers] do
    member do
      get :following, :followers
    end
  end
  resources :microposts
  resources :subcategories, only: [:show]
  resources :scores, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :infos, only: :index
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :user_id, presence: true
  validates :title,   presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :subcategory
  has_many :scores, dependent: :destroy
  has_many :replies, dependent: :destroy

  def self.search(search)
    if search
      Micropost.where(['content LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Micropost.all
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @microposts = Micropost.all.order('created_at desc').page(params[:page]).per(5)
  end

  def show
    @micropost = Micropost.find(params[:id])
    @user = @micropost.user
    @score = Score.new
    @reply = Reply.new
    @replies = @micropost.replies.page(params[:page]).per(5)
  end

  def new
    @micropost = Micropost.new
  end

  def search
    @microposts = Micropost.search(params[:search]).order('created_at desc').page(params[:page]).per(5)
    @categories = Category.all
    render "microposts/index"
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    youtube_url = params[:micropost][:url]
    youtube_url = youtube_url.last(11)
    @micropost.url = youtube_url

    if @micropost.save
      flash[:success] = "投稿が完了しました"
      redirect_to @micropost
    else
      flash[:danger] = "投稿に失敗しました"
      render "new"
    end
  end

  def edit
  end

  def update
    youtube_url = params[:micropost][:url]
    youtube_url = youtube_url.last(11)
    @micropost.url = youtube_url

    if @micropost.update_attributes(micropost_params)
      flash[:success] = "編集が完了しました"
      redirect_to @micropost
    else
      flash[:danger] = "編集に失敗しました"
      render "edit"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to microposts_path
  end
  private

    def micropost_params
      params.require(:micropost).permit(:content, :url, :title, :subcategory_id)
    end

    def correct_user
      @micropost =Micropost.find(params[:id])
      redirect_to root_url unless @micropost.user == current_user
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <%= link_to user_path(micropost.user) do %>
        <img src=<%= micropost.user.image %> class = "icon_mini_image">
        <h3><%= micropost.user.name %></h3>
      <% end %>
      <%= link_to micropost_path(micropost) do %>
        <button type="button" class="btn btn-default btn-lg">
          <span class="far fa-star"></span> <%= average_score(micropost) %>
        </button>
      <% end %>
    </div>
  <div class="panel-body panel_micropost">
      <h3><%=link_to micropost.title, micropost_path(micropost) %></h3>
      <hr>
      <p><iframe width="352" height="198" src="https://www.youtube.com/embed/<%= micropost.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
      <% if micropost.user == current_user %>
        <h5>
          <%= link_to "編集する", edit_micropost_path(micropost) %> |
          <%= link_to "削除する", micropost, method: :delete, data: {confirm:"本当に削除しますか？"} %>
        </h5>
      <% end %>
  </div>
</div>

app/views/microposts/edit.html.erb
<%= render "micropost", micropost: @micropost %>
<%= form_for(@micropost) do |f| %>

<div class="form-group">
  <%= f.label :title, "タイトル" %><br />
  <%= f.text_field :title, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :url, "youtubeのURL" %>
  <%= f.text_field :url, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :content, "説明" %>
  <%= f.text_field :content, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :subcategory_id, "カテゴリ" %>
  <%= f.select :subcategory_id, Subcategory.all.map{|o| ["#{o.category.name}|#{o.name}", o.id]} %>
</div>

<div class="form-group">
  <%= f.submit "編集を確定", class: 'btn btn-primary' %>
</div>

<% end %>

app/views/microposts/index.html.erb
<% provide(:title, "動画一覧") %>
<div clas="row">
  <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
    <div class="panel panel-primary">
      <div class="panel-heading">カテゴリー</div>
      <div class="panel-body">
        <ul class="nav  side-nav">
          <% @categories.each do |category| %>
          <li>
              <%= category.name %>
            <ul>
              <% category.subcategories.each do |subcategory| %>
                <li>
                  <%= link_to subcategory_path(subcategory.id) do %>
                    <%= "#{subcategory.name}(#{subcategory.microposts.count})" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-9 col-sm-8 col-xs-12">
    <div class="form-group form-search row">
      <%= form_tag(search_path, method:'get') do %>
        <div class=" col-xs-9">
          <%= text_field_tag :search, params[:search], class:"form-control" %>
        </div>
        <div class="col-xs-3">
          <%= submit_tag '検索', class:"btn btn-primary " %>
        </div>
      <% end %>
    </div>
    <%= render @microposts %>
    <%= paginate @microposts %>
  </div>
</div>

app/views/microposts/new.html.erb
<%= form_for(@micropost) do |f| %>

<div class="form-group">
  <%= f.label :title, "タイトル" %><br />
  <%= f.text_field :title, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :url, "youtubeのURL" %>
  <%= f.text_field :url, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :content, "説明" %>
  <%= f.text_field :content, autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :subcategory_id, "カテゴリ" %>
  <%= f.select :subcategory_id, Subcategory.all.map{|o| ["#{o.category.name}|#{o.name}", o.id]} %>
</div>

<div class="form-group">
  <%= f.submit "投稿する", class: 'btn btn-primary' %>
</div>

<% end %>

app/views/microposts/show.html.erb
<% provide(:title, @micropost.title) %>
<div class="panel panel-default panel-mic-show">
  <div class="panel-heading reply-heading">
    <%= link_to @user do %>
      <img src=<%= @user.image %> class = "icon_mini_image">
      <h3><%= @user.name %></h3>
    <% end %>
    <button type="button" class="btn btn-default btn-sm">
      <span class="far fa-star"></span> <%= average_score(@micropost) %>
    </button>
    <% if @micropost.subcategory %>
      <%= link_to @micropost.subcategory do %>
        <button type="button" class="btn btn-default btn-sm">
          <span></span> <%= "#{@micropost.subcategory.category.name}|#{@micropost.subcategory.name}" %>
        </button>
      <% end %>
    <% end %>
  </div>
  <div class="panel-body panel_micropost">
    <h1><%= @micropost.title %></h1>
    <hr>
    <p>
      <iframe width="448" height="252" src="https://www.youtube.com/embed/<%= @micropost.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </p>
    <h4><%= @micropost.content %></h4>
    <% if @micropost.user == current_user %>
      <h5>
        <%= link_to "編集する", edit_micropost_path(@micropost) %> |
        <%= link_to "削除する", @micropost, method: :delete, data: {confirm:"本当に削除しますか？"} %>
      </h5>
    <% end %>
    <hr>
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-xs-8">
          <%= form_for(@reply) do |f| %>
            <div class="form-group">
              <%= f.text_field :content, autofocus: true, class: "form-control" %>
            </div>
            <%= hidden_field_tag :micropost_id, @micropost.id %>
            <div class="form-group">
              <%= f.submit "返信する", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="col-xs-4">
          <% if Score.where(user_id: current_user.id, micropost_id: @micropost.id).blank? %>
            <%= form_for(@score) do |f| %>
              <div class="form-group">
                <%= f.label :point, "point" %>
                <%= f.select :point, (1..5).to_a.map{|i| ["#{i}",i]} %>
              </div>
              <%= hidden_field_tag :micropost_id, @micropost.id %>
              <div class="form-group">
                <%= f.submit "採点する", class: 'btn btn-primary' %>
              </div>
            <% end %>
          <% else %>
           <h4>採点済み</h4>
          <% end %>
        </div>
      </div>
    <% else %>
    <h3>
      <%= link_to "ログイン", new_user_session_path %>
      することで動画への返信、採点が可能です
    </h3>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
  <%= render @replies %>
  </div>
</div>