config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "staticpages#home"
  get "/help", to: "staticpages#help"
  get "/terms", to: "staticpages#terms"
  get "/contact", to: "staticpages#contact"
  get "/search", to: "microposts#search"
  get "/sample", to: "users#sample"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :following, :followers] do
    member do
      get :following, :followers
    end
  end
  resources :microposts
  resources :subcategories, only: [:show]
  resources :scores, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create, :destroy]
  resources :infos, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
end

app/models/info.rb
class Info < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  def action_user
    User.find(self.action_user_id)
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :user_id, presence: true
  validates :title,   presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :subcategory
  has_many :scores, dependent: :destroy
  has_many :replies, dependent: :destroy

  def self.search(search)
    if search
      Micropost.where(['content LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Micropost.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  validates  :content, presence: true
  belongs_to :micropost
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :microposts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :profile, length: { maximum: 200 }
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :replies, dependent: :destroy
  has_many :infos, dependent: :destroy

   def self.find_for_oauth(auth)
     user = User.where(uid: auth.uid, provider: auth.provider).first
     unless user
       user = User.create(
         uid:      auth.uid,
         provider: auth.provider,
         email:    User.dummy_email(auth),
         name:  auth.info.name,
         password: Devise.friendly_token[0, 20],
         remote_image_url:  auth.info.image.gsub("picture","picture?type=large")
       )
     end
     user
   end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

   private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :authenticate_user!

  def index
    @infos = current_user.infos.page(params[:page]).per(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at desc').page(params[:page]).per(5)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  def sample
    sample_user = User.find(1)
    sign_in sample_user
    flash[:success] = "サンプルユーザーでのログインに成功しました"
    redirect_to sample_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "わらログ"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def average_score(micropost)
    sum = micropost.scores.sum(&:point)
    count = Score.where('cast(micropost_id as text) LIKE ?', "#{micropost.id}").count
    if count != 0
      (sum * 1.0/count * 1.0 ).round(1)
    else
      0
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse footer">
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "利用規約", terms_path %></li>
    <li><%= link_to "お問い合わせ", contact_path %></li>
  </ul>
  <h4>&copy; わらログ 2020</h4>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "わらログ", root_path, class:"navbar-brand active" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "マイページ", user_path(current_user) %></li>
          <li><%= link_to "動画一覧", microposts_path %></li>
          <li><%= link_to "通知", infos_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "動画一覧", microposts_path %></li>
          <li><%= link_to "ヘルプ", help_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>